:tea:
  :categories:
    :puerh:
      :raw: raw_puerh
      :ripe: ripe_puerh
    :teguanin: teguanin
    :other: other

:user:
  :lists:
    - :tried
    - :want_by

:axis:
  :names:
    - :high
    - :flavor
    - :unusual
    - :quality
  :grade:
    - 10
